import java.util.ArrayList;
import java.util.Random;

public class Frank {

	private String target;
	private ArrayList<String> guesses;
	
	public static final int FRANK_WORD_LENGTH = 5;
	
	public Frank() {
		target = getRandom5LetterWord();
		guesses = new ArrayList<String>();
	}
	
	
	//public void guessWord(String play) {
	public void guess(String play) {
		if (play.length() == FRANK_WORD_LENGTH) {
			play = play.toLowerCase();
			int matches = getNumMatches(play);
			String guess = play + " " + matches;
			if (!guesses.contains(guess)) {
				guesses.add(guess);
			}
		}
	}
	
	private int getNumMatches(String play) {
		int count = 0;
		for (int i = 0; i < target.length(); i++) {
			if (play.charAt(i) == target.charAt(i)) {
				count++;
			}
		}
		return count;
	}

	//public boolean lastGuessMatched() {
	public boolean isOver() {
		return target.equals(getRecentPlay());
	}
	
	private String getRecentPlay() {
		int last = guesses.size() - 1;
		if (last == -1) {
			return "";
		}
		
		String lastGuess = guesses.get(last);
		return lastGuess.substring(0, FRANK_WORD_LENGTH);
	}

	//public String getGuesses() {
	public String getStatus() {
		if (isOver()) {
			return "You win in " + guesses.size() + " guesses! \u266B Hooray! \u266A";
		}
		int numGuesses = guesses.size();
		if (numGuesses == 0) {
			return "It is your first guess.";
		}

		String status =   "Guess Matches\n";
		status = status + "----- -------\n";
		for (String guess : guesses) {
			status = status + guess + "\n";
		}
		return status;
	}
	
	@Override 
	public String toString() {
		return getClass().getName() + "[target=" + target + "]";
	}

	
	
	
	// Get any of the 5-letter words appearing in a
	// standard list of the 3000 most common English words,
	// as reported in Browne, C., Culligan, B. & Phillips, J. (2013),
	// The New General Service List. http://www.newgeneralservicelist.org

	// Specific list used is first three tabs (sheets) of
	// http://www.newgeneralservicelist.org/s/NGSL-101-by-band-qq9o.xlsx

	private String getRandom5LetterWord() {

		String[] words = {
				"about",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
				"above",
				"abuse",
				"actor",
				"adapt",
				"admit",
				"adopt",
				"adult",
				"after",
				"again",
				"agent",
				"agree",
				"ahead",
				"alarm",
				"album",
				"alive",
				"allow",
				"alone",
				"along",
				"alter",
				"amaze",
				"among",
				"anger",
				"angle",
				"angry",
				"apart",
				"apply",
				"argue",
				"arise",
				"aside",
				"asset",
				"avoid",
				"award",
				"aware",
				"awful",
				"badly",
				"basic",
				"basis",
				"beach",
				"begin",
				"below",
				"birth",
				"black",
				"blame",
				"bless",
				"blind",
				"block",
				"blood",
				"board",
				"boost",
				"brain",
				"brand",
				"bread",
				"break",
				"breed",
				"brief",
				"bring",
				"broad",
				"brown",
				"brush",
				"build",
				"bunch",
				"burst",
				"buyer",
				"cable",
				"carry",
				"catch",
				"cause",
				"chain",
				"chair",
				"charm",
				"chart",
				"chase",
				"cheap",
				"check",
				"cheek",
				"chest",
				"chief",
				"child",
				"civil",
				"claim",
				"class",
				"clean",
				"clear",
				"climb",
				"clock",
				"close",
				"cloud",
				"coach",
				"coast",
				"color",
				"cough",
				"could",
				"count",
				"court",
				"cover",
				"crack",
				"craft",
				"crash",
				"crazy",
				"cream",
				"crime",
				"cross",
				"crowd",
				"curve",
				"cycle",
				"daily",
				"dance",
				"death",
				"delay",
				"depth",
				"dirty",
				"doubt",
				"dozen",
				"draft",
				"drama",
				"dream",
				"dress",
				"drink",
				"drive",
				"early",
				"earth",
				"elect",
				"email",
				"empty",
				"enemy",
				"enjoy",
				"enter",
				"entry",
				"equal",
				"error",
				"essay",
				"event",
				"every",
				"exact",
				"exist",
				"extra",
				"faith",
				"false",
				"fancy",
				"fault",
				"favor",
				"fence",
				"field",
				"fight",
				"final",
				"first",
				"flash",
				"float",
				"flood",
				"floor",
				"focus",
				"force",
				"forth",
				"found",
				"frame",
				"fresh",
				"front",
				"fruit",
				"fully",
				"funny",
				"giant",
				"glass",
				"grade",
				"grain",
				"grand",
				"grant",
				"grass",
				"great",
				"green",
				"greet",
				"group",
				"guard",
				"guess",
				"guest",
				"guide",
				"habit",
				"happy",
				"heart",
				"heavy",
				"hello",
				"hence",
				"honor",
				"horse",
				"hotel",
				"house",
				"human",
				"humor",
				"hurry",
				"ideal",
				"image",
				"imply",
				"index",
				"inner",
				"input",
				"issue",
				"joint",
				"judge",
				"knife",
				"knock",
				"label",
				"labor",
				"large",
				"laugh",
				"layer",
				"learn",
				"least",
				"leave",
				"legal",
				"level",
				"light",
				"limit",
				"local",
				"logic",
				"loose",
				"lover",
				"lucky",
				"lunch",
				"magic",
				"major",
				"maker",
				"march",
				"marry",
				"match",
				"maybe",
				"mayor",
				"metal",
				"meter",
				"might",
				"minor",
				"model",
				"money",
				"month",
				"moral",
				"motor",
				"mount",
				"mouse",
				"mouth",
				"movie",
				"music",
				"nerve",
				"never",
				"newly",
				"night",
				"noise",
				"north",
				"novel",
				"nurse",
				"occur",
				"ocean",
				"offer",
				"often",
				"opera",
				"order",
				"other",
				"ought",
				"owner",
				"paint",
				"panel",
				"panic",
				"paper",
				"party",
				"pause",
				"peace",
				"phase",
				"phone",
				"photo",
				"piano",
				"piece",
				"pilot",
				"pitch",
				"place",
				"plain",
				"plane",
				"plant",
				"plate",
				"point",
				"pound",
				"power",
				"press",
				"price",
				"pride",
				"prime",
				"print",
				"prior",
				"prize",
				"proof",
				"proud",
				"prove",
				"pupil",
				"quick",
				"quiet",
				"quite",
				"quote",
				"radio",
				"raise",
				"range",
				"rapid",
				"ratio",
				"reach",
				"react",
				"ready",
				"refer",
				"relax",
				"reply",
				"right",
				"rival",
				"river",
				"rough",
				"round",
				"route",
				"royal",
				"rural",
				"scale",
				"scare",
				"scene",
				"scope",
				"score",
				"sense",
				"serve",
				"shade",
				"shake",
				"shall",
				"shape",
				"share",
				"sharp",
				"sheep",
				"sheet",
				"shelf",
				"shell",
				"shift",
				"shine",
				"shirt",
				"shock",
				"shoot",
				"shore",
				"short",
				"shout",
				"sight",
				"silly",
				"since",
				"skill",
				"skirt",
				"slave",
				"sleep",
				"slice",
				"slide",
				"slope",
				"small",
				"smart",
				"smell",
				"smile",
				"smoke",
				"solid",
				"solve",
				"sorry",
				"sound",
				"south",
				"space",
				"spare",
				"speak",
				"speed",
				"spell",
				"spend",
				"split",
				"sport",
				"staff",
				"stage",
				"stain",
				"stair",
				"stake",
				"stamp",
				"stand",
				"stare",
				"start",
				"state",
				"steal",
				"steel",
				"stick",
				"still",
				"stock",
				"stone",
				"store",
				"storm",
				"story",
				"strip",
				"study",
				"stuff",
				"style",
				"sugar",
				"swear",
				"sweep",
				"sweet",
				"swing",
				"table",
				"taste",
				"teach",
				"thank",
				"theme",
				"there",
				"thick",
				"thing",
				"think",
				"throw",
				"tight",
				"title",
				"today",
				"tooth",
				"topic",
				"total",
				"touch",
				"tough",
				"tower",
				"trace",
				"track",
				"trade",
				"trail",
				"train",
				"treat",
				"trend",
				"trial",
				"trick",
				"troop",
				"truck",
				"truly",
				"trust",
				"truth",
				"twice",
				"twist",
				"uncle",
				"under",
				"union",
				"unite",
				"until",
				"upper",
				"upset",
				"urban",
				"usual",
				"value",
				"video",
				"virus",
				"visit",
				"vital",
				"voice",
				"voter",
				"waste",
				"watch",
				"water",
				"weigh",
				"weird",
				"wheel",
				"where",
				"which",
				"while",
				"white",
				"whole",
				"woman",
				"world",
				"worry",
				"worth",
				"would",
				"wound",
				"write",
				"wrong",
				"yield",
				"young",
				"youth"				
		};
		
		Random r = new Random();
		return words[r.nextInt(words.length)];
	}

}
